#!/usr/bin/with-contenv bash

# If we are debugging, enable trace
if [ "${DEBUG,,}" = "true" ]; then
  set -x
fi

function getPref {
  local key="$1"
  
  xmlstarlet sel -T -t -m "/Preferences" -v "@${key}" -n "${prefFile}"
}

function setPref {
  local key="$1"
  local value="$2"
  
  count="$(xmlstarlet sel -t -v "count(/Preferences/@${key})" "${prefFile}")"
  count=$(($count + 0))
  if [[ $count > 0 ]]; then
    xmlstarlet ed --inplace --update "/Preferences/@${key}" -v "${value}" "${prefFile}"
  else
    xmlstarlet ed --inplace --insert "/Preferences"  --type attr -n "${key}" -v "${value}" "${prefFile}"
  fi
}

rar2fs --seek-length=1 -o allow_other /media_hds /media
rar2fs --seek-length=1 -o allow_other /media_series /media2
rar2fs --seek-length=1 -o allow_other /media_uhds /media3
rar2fs --seek-length=1 -o allow_other /media_vids /media4

echo "Rar2fs setup complete - Mounted media drives"
